# Generated by Django 5.0.2 on 2024-02-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_image', verbose_name='تصویر محصول')),
            ],
            options={
                'verbose_name': 'عکس پروژه',
                'verbose_name_plural': 'عکس پروژه ها',
            },
        ),
    ]
