# Generated by Django 5.0 on 2024-02-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companymodel_alter_productmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سرویس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_image', verbose_name='تصویر سرویس')),
            ],
            options={
                'verbose_name': 'عکس سرویس در صفحه اول',
                'verbose_name_plural': 'عکس سرویس ها در صفحه اول',
            },
        ),
    ]
