# Generated by Django 5.0 on 2024-02-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_abilitycameramodel_alter_companymodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام زبان برنامه نویسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='program_image', verbose_name='تصویر زبان برنامه نویسی')),
            ],
            options={
                'verbose_name': 'عکس زبان برنامه نویسی',
                'verbose_name_plural': 'عکس زبان برنامه نویسی',
            },
        ),
    ]
