# Generated by Django 5.0.2 on 2024-02-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_name_cameramodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کمپانی سازنده دوربین')),
            ],
            options={
                'verbose_name': 'عکس کمپانی سازنده دوربین',
                'verbose_name_plural': 'عکس کمپانی های سازنده دوربین',
            },
        ),
        migrations.AlterField(
            model_name='cameramodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cameracategorymodel', verbose_name='شرکت سازنده دوربین'),
        ),
    ]
