# Generated by Django 5.0.2 on 2024-03-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_cameracategorymodel_alter_cameramodel_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardHomeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="سر تیتر")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
            ],
            options={
                "verbose_name": "کادر صفحه اول",
                "verbose_name_plural": "کادر صفحه اول",
            },
        ),
    ]
