# Generated by Django 5.0.3 on 2024-03-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_socialmediamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='نام')),
                ('email', models.CharField(max_length=50, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=50, verbose_name='شماره موبایل')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباط با ما',
            },
        ),
    ]
