# Generated by Django 5.0.2 on 2024-03-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_contactmemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmediamodel",
            name="link",
            field=models.CharField(
                default="", max_length=50, verbose_name="لینک شبکه اجتماعی"
            ),
            preserve_default=False,
        ),
    ]
